name: Lint

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-gv5
      with:
        go-version: '1.22'
    - name: Checkout
      uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58
        args: --timeout 5m
