name: Lint

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3.5.0
      with:
        go-version: '1.19.5'
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.3.1
      with:
        version: v1.50
        args: --timeout 5m
